apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user who can view but not edit any resources within
      the project. They can not view membership.
  creationTimestamp: null
  name: view-plus-secrets
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - secrets
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - bindings
  - events
  - limitranges
  - namespaces
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  attributeRestrictions: null
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  attributeRestrictions: null
  resources:
  - cronjobs
  - jobs
  - scheduledjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - deployments
  - deployments/scale
  - horizontalpodautoscalers
  - jobs
  - replicasets
  - replicasets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  attributeRestrictions: null
  resources:
  - deployments
  - deployments/scale
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - buildconfigs
  - buildconfigs/webhooks
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - builds/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - jenkins
  verbs:
  - view
- apiGroups:
  - apps.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - deploymentconfigs/log
  - deploymentconfigs/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - imagestreamimages
  - imagestreammappings
  - imagestreams
  - imagestreamtags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - imagestreams/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - projects
  verbs:
  - get
- apiGroups:
  - quota.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - appliedclusterresourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - routes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - processedtemplates
  - templateconfigs
  - templateinstances
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - buildlogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - resourcequotausages
  verbs:
  - get
  - list
  - watch
